export const EDITORIAL_PLAN = [
    { topic: 'fiducia', title: 'In allenamento è un altro: perché in partita ha paura di sbagliare', query: 'mio figlio in partita si blocca', angle: 'Capire che cosa succede tra il primo errore e la giocata successiva.', slug: 'paura-di-sbagliare-nel-calcio', evidence: 'Advertorial già sviluppato: pochi-minuti.' },
    { topic: 'panchina', title: 'Mio figlio gioca poco: come stargli vicino senza aumentare la pressione', query: 'mio figlio non gioca mai a calcio', angle: 'Distinguere minutaggio, fiducia e confronto con l’allenatore.', slug: 'mio-figlio-gioca-poco', evidence: 'Tema emerso nella ricerca sui genitori.' },
    { topic: 'crescita', title: 'È salito di categoria, ma ha perso fiducia: da dove ripartire', query: 'calcio cambio squadra perdita fiducia', angle: 'Nuovo livello, nuove aspettative, bisogno di ambientarsi.', slug: 'salto-di-categoria-fiducia', evidence: 'Due racconti familiari nella ricerca: ingresso in Eccellenza e club professionistico.' },
    { topic: 'genitori', title: 'Che cosa dire a un figlio dopo una brutta partita', query: 'cosa dire a un figlio dopo una sconfitta', angle: 'Ascolto, momento giusto e domande che aprono una conversazione.', slug: 'cosa-dire-dopo-brutta-partita', evidence: 'Tema del rapporto genitore e figlio documentato nella ricerca.' },
    { topic: 'fiducia', title: 'Un errore e si spegne: come affrontare la perdita di fiducia in campo', query: 'fiducia dopo errore calcio', angle: 'Separare un episodio dal giudizio complessivo su di sé.', slug: 'fiducia-dopo-errore-calcio', evidence: 'Approfondimento del primo articolo; evitare contenuti duplicati.' },
    { topic: 'pressione', title: 'Prima della partita è già sotto pressione: che cosa può osservare un genitore', query: 'agitazione prima partita figlio', angle: 'Riconoscere situazioni ricorrenti e ascoltare il punto di vista del ragazzo.', slug: 'pressione-prima-della-partita', evidence: 'Tema del metodo; domanda SEO da verificare.' },
    { topic: 'ripartenza', title: 'Dopo un infortunio teme di perdere il posto: come accompagnarlo', query: 'paura dopo infortunio calcio', angle: 'Il vissuto del fermo e del rientro, nel rispetto del percorso sanitario.', slug: 'paura-rientro-infortunio-calcio', evidence: 'Episodio d’acquisto specifico emerso nella ricerca.' },
    { topic: 'ripartenza', title: 'Mio figlio non si diverte più a calcio: ascoltare prima di decidere', query: 'mio figlio vuole lasciare calcio', angle: 'Capire che cosa è cambiato senza dare per scontato che debba continuare.', slug: 'figlio-non-si-diverte-calcio', evidence: 'Calo della passione documentato; intenzione di abbandonare da verificare.' },
    { topic: 'genitori', title: 'Tra incoraggiamento e pressione: il ruolo del genitore in tribuna', query: 'genitori pressione figli calcio', angle: 'Distinguere il sostegno dalle aspettative e rispettare i ruoli.', slug: 'genitori-pressione-calcio', evidence: 'Tema presente nel percorso Metodo Sincro.' },
    { topic: 'crescita', title: 'Restare o cambiare squadra quando tuo figlio trova poco spazio?', query: 'cambiare squadra figlio non gioca', angle: 'Domande da valutare insieme, senza una risposta universale.', slug: 'cambiare-squadra-poco-spazio', evidence: 'Dilemma emerso nelle discussioni analizzate, da approfondire nel contesto italiano.' },
    { topic: 'pressione', title: 'Provini e selezioni: prepararsi senza trasformare tutto in un esame', query: 'paura provino calcio', angle: 'Aspettative, attenzione ai compiti e valutazione dell’esperienza.', slug: 'pressione-provino-calcio', evidence: 'Ipotesi editoriale: raccogliere casi e domande del team.' },
    { topic: 'genitori', title: 'Mental coaching per un giovane calciatore: che cosa succede davvero', query: 'mental coaching calcio ragazzi come funziona', angle: 'Sessioni, ruolo del ragazzo, coinvolgimento della famiglia e impegno richiesto.', slug: 'mental-coaching-calcio-ragazzi', evidence: 'Descrizione del servizio in AV Brain, da allineare alla proposta attuale.' },
] as const
