'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { Plus, ArrowUpRight, Search, FileText, BookOpen, ListChecks } from 'lucide-react'
import { BLOG_TOPICS, type BlogInput, type BlogPost, type LegacyArticle } from '@/lib/blog'
import { EDITORIAL_PLAN } from '@/lib/blog-editorial'
import BlogEditor, { emptyArticle } from './BlogEditor'
import styles from './blog-admin.module.css'

export default function BlogPanel({ initialPosts, legacy, loadError = '', demo = false }: { initialPosts: BlogPost[]; legacy: LegacyArticle[]; loadError?: string; demo?: boolean }) {
    const [posts, setPosts] = useState(initialPosts)
    const [tab, setTab] = useState<'articles' | 'plan'>('articles')
    const [status, setStatus] = useState('all')
    const [search, setSearch] = useState('')
    const [editing, setEditing] = useState<BlogInput | BlogPost | null>(null)
    const [notice, setNotice] = useState('')
    const visible = useMemo(() => posts.filter(post => (status === 'all' || post.status === status) && `${post.title} ${post.excerpt}`.toLocaleLowerCase('it').includes(search.toLocaleLowerCase('it'))), [posts, status, search])
    function save(post: BlogPost) { setPosts(items => [post, ...items.filter(item => item.id !== post.id)]); setNotice(post.status === 'active' ? 'Articolo pubblicato. L’indicizzazione va verificata in Search Console.' : 'Bozza salvata.'); }
    if (editing) return <BlogEditor key={'id' in editing ? editing.id : editing.slug} initial={editing} onClose={() => setEditing(null)} onSaved={save} demo={demo} />
    return <main className={styles.panel}>
        {demo && <p className={styles.notice}>Anteprima locale del Blog nel gestionale · Dati dimostrativi · Salvataggio e pubblicazione disabilitati</p>}
        <div className={styles.heading}><div><p className={styles.overline}>MARKETING / CONTENUTI</p><h1>Blog<span>Dentro la partita</span></h1><p>Le domande dei genitori, un articolo alla volta.</p></div><div className={styles.actions}><a href={demo ? '/blog/anteprima' : '/blog'} target="_blank" rel="noopener noreferrer">Apri il blog <ArrowUpRight size={16} /></a><button className={styles.primary} disabled={!!loadError} onClick={() => setEditing({ ...emptyArticle })}><Plus size={17} /> Nuovo articolo</button></div></div>
        {loadError && <div className={styles.error} role="alert"><strong>Collegamento al Blog non disponibile.</strong><p>{loadError} I contenuti salvati non sono stati modificati.</p><button onClick={() => window.location.reload()}>Riprova</button></div>}
        {notice && <p role="status" className={styles.notice}>{notice}</p>}
        <div className={styles.stats}><div><strong>{posts.filter(post => post.status === 'active').length + legacy.filter(post => post.status === 'active').length}</strong><span>Articoli pubblicati</span></div><div><strong>{posts.filter(post => post.status === 'draft').length}</strong><span>Bozze in lavorazione</span></div><div><strong>{EDITORIAL_PLAN.length}</strong><span>Temi nel piano editoriale</span></div><p>Contenuti di Metodo Sincro.<br />Un’unica area per blog e advertorial.</p></div>
        <div className={styles.tabs} role="tablist" aria-label="Sezioni del Blog"><button role="tab" aria-selected={tab === 'articles'} onClick={() => setTab('articles')}><BookOpen size={17} /> Articoli</button><button role="tab" aria-selected={tab === 'plan'} onClick={() => setTab('plan')}><ListChecks size={17} /> Piano editoriale</button></div>
        {tab === 'articles' ? <section>
            <div className={styles.filters}><label className={styles.search}><Search size={16} /><input aria-label="Cerca articoli" placeholder="Cerca un articolo…" value={search} onChange={event => setSearch(event.target.value)} /></label><select aria-label="Filtra per stato" value={status} onChange={event => setStatus(event.target.value)}><option value="all">Tutti gli stati</option><option value="draft">Bozze</option><option value="active">Pubblicati</option><option value="archived">Archiviati</option></select></div>
            {visible.length > 0 ? <div className={styles.articleList}>{visible.map(post => <article key={post.id}><div><span className={styles.badge} data-active={post.status === 'active'}>{post.status === 'active' ? 'Pubblicato' : post.status === 'archived' ? 'Archiviato' : 'Bozza'}</span><span className={styles.topic}>{BLOG_TOPICS.find(topic => topic.id === post.topic)?.label}</span><h2><button onClick={() => setEditing(post)}>{post.title}</button></h2><p>{post.excerpt || 'L’introduzione è ancora da scrivere.'}</p><small>{post.seoTitle && post.seoDescription ? 'Campi SEO compilati' : 'Campi SEO da completare'}</small></div><div className={styles.rowActions}><button onClick={() => setEditing(post)}>Apri editor <ArrowUpRight size={15} /></button>{post.status === 'active' && <a href={`/blog/${post.slug}`} target="_blank" rel="noopener noreferrer">Vedi articolo ↗</a>}</div></article>)}</div> : <div className={styles.empty}><FileText size={27} /><h2>{search || status !== 'all' ? 'Nessun articolo con questi filtri.' : 'Il prossimo articolo comincia da una domanda.'}</h2><p>{search || status !== 'all' ? 'Prova un altro testo o cambia lo stato.' : 'Crea una bozza oppure scegli un tema dal piano editoriale.'}</p>{!search && status === 'all' && <button onClick={() => setTab('plan')}>Esplora il piano editoriale →</button>}</div>}
            {legacy.length > 0 && <section className={styles.legacy}><div><h2>Advertorial esistenti</h2><p>Pagine già collegate ai funnel. Mantengono i loro indirizzi e la gestione attuale.</p></div>{legacy.map(article => <article key={article.id}><div><span className={styles.badge} data-active={article.status === 'active'}>{article.status === 'active' ? 'Pubblicato' : article.status === 'draft' ? 'Bozza' : 'Non pubblico'}</span><h3>{article.title}</h3><small>/f/{article.slug}</small></div><div className={styles.rowActions}>{article.status === 'active' && <a href={`https://landing.metodosincro.com/f/${article.slug}?ab=A`} target="_blank" rel="noopener noreferrer">Apri pagina ↗</a>}<a href="/dashboard/funnels">Gestisci nel Funnel ↗</a>{article.slug === 'pochi-minuti' && demo && <Link href="/f/pochi-minuti/anteprima">Vedi revisione V3 ↗</Link>}</div></article>)}</section>}
        </section> : <section className={styles.plan}><div className={styles.planIntro}><h2>Partiamo dalle situazioni che vivono.</h2><p>12 temi per costruire una biblioteca utile ai genitori. Le domande SEO sono ipotesi da verificare: non rappresentano volumi di ricerca misurati. Ogni scheda avvia una bozza da sviluppare e revisionare.</p></div>{EDITORIAL_PLAN.map((item, i) => <article key={item.slug}><span className={styles.number}>{String(i + 1).padStart(2, '0')}</span><div><p className={styles.overline}>{BLOG_TOPICS.find(topic => topic.id === item.topic)?.label}</p><h3>{item.title}</h3><p>{item.angle}</p><small>Domanda da verificare: «{item.query}»</small><p className={styles.evidence}>{item.evidence}</p></div><button disabled={!!loadError} onClick={() => { const existing = posts.find(post => post.slug === item.slug); setEditing(existing || { ...emptyArticle, title: item.title, slug: item.slug, topic: item.topic, excerpt: item.angle, seoTitle: item.title.slice(0, 100) }) }}>{posts.some(post => post.slug === item.slug) ? 'Apri bozza' : 'Prepara articolo'} <ArrowUpRight size={15} /></button></article>)}</section>}
    </main>
}
